# Generated by Django 4.2.1 on 2023-05-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute_share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationmodel',
            name='id_card_back',
            field=models.ImageField(upload_to='id-card-back/'),
        ),
        migrations.AlterField(
            model_name='verificationmodel',
            name='id_card_front',
            field=models.ImageField(upload_to='id-card-front/'),
        ),
        migrations.AlterField(
            model_name='verificationmodel',
            name='photograph',
            field=models.ImageField(upload_to='images1'),
        ),
    ]
