# Generated by Django 4.2.1 on 2023-06-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commute_share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commute_share.books')),
            ],
        ),
    ]
