# Generated by Django 4.2.1 on 2023-05-30 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commute_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createride',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commute_share.drivermodel'),
            preserve_default=False,
        ),
    ]
