# Generated by Django 4.2.1 on 2023-05-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute_share', '0002_alter_verificationmodel_id_card_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationmodel',
            name='id_card_back',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='verificationmodel',
            name='photograph',
            field=models.ImageField(upload_to=''),
        ),
    ]
