# Generated by Django 4.2.1 on 2023-06-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commute_share', '0002_remove_drivermodel_identity_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivermodel',
            name='car',
        ),
        migrations.RemoveField(
            model_name='drivermodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='drivermodel',
            name='verification',
        ),
    ]
