# Generated by Django 4.2.1 on 2023-05-30 12:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('commute_share', '0003_checkdrivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkdrivers',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
